language: python
python:
  - '3.7'
script:
  - git clone -b gh-pages https://github.com/gggxbbb/TuPics.git build
  - pip3 install Jinja2
  - pip3 install pytz
  - python3 run.py
after_success:
  - cd build/
  - git add -- *; git commit --allow-empty-message -m ""
  - git push -f -q https://gggxbbb:$GITHUB_PASS@github.com/gggxbbb/TuPics.git master:gh-pages
cache:
  directories:
    - build
notifications:
  email:
    - 2331490629@qq.com
