language: python
python:
  - '3.7'
install:
  - pip3 install Jinja2
  - pip3 install pytz
  - pip3 install xlwt
  - pip3 install requests
  - pip3 install gfm
script:
  - python3 run.py
  - python3 excel.py
  - cp static/* build
after_success:
  - cd build/
  - git config http.postBuffer 524288000
  - git init; git add -- *; git commit --allow-empty-message -m ""
  - git push -f -q https://gggxbbb:$GITHUB_PASS@github.com/gggxbbb/TuPics.git master:gh-pages
cache:
  directories:
    - build
notifications:
  email:
    - 2331490629@qq.com
